### ISSUE TITLE
How to integrate using pipeline Jenkins script

### ISSUE THREAD

**Issue by odcnre** [CiscoTestAutomation/jenkins_project_plugin#1]
I am looking for pipeline support.
The plugin works with freestyle projects but my job is pipeline.

**Comment by ke-liu** [comment]
Hello,
If pipeline supports DSL/Groovy based scripts as it’s previous generation - Build Flow (https://wiki.jenkins.io/display/JENKINS/Build+Flow+Plugin), you can easily involve the pyATS Projects into your pipeline project.

Example DSL script below shows the run that includes 3 pyATS jobs and 1 free style job.
* create a pyATS job - cleanRouter1
* create a pyATS job - cleanRouter2
* create a pyATS job - runPyatsScript
* Create a free style job - tearDown

DSL script in pipeline:

>     Parallel (
> 	    {build (“cleanRouter1”)},
> 	    {build(“cleanRouter2”)},
>     )
>     build(“runPyatsScript”)
>     build(“tearDown”)

pyATS project jobs are same as free style jobs, whatever you do to include free style jobs in your pipeline, you can expect the same way for pyATS jobs.
