### ISSUE TITLE
Minimum Memory Requirements?

### ISSUE THREAD

**Issue by udaykumar-8329** [CiscoTestAutomation/jenkins_project_plugin#2]
Hi Team,

What are the minimum memory requirements for this plugin to work?

**Comment by SohanTirpude** [comment]
Hello @udaykumar-8329,

I will be working on your ticket. I'll get back to you once I have any update on it.

**Comment by SohanTirpude** [comment]
Hello @udaykumar-8329, as far as I know, there is no exact memory requirements for this plugins but you may try with 4GB of RAM. And anyway, the memory depends on how memory intrinsic operation you are performing. Kindly let me know if you have any questions.

**Comment by SohanTirpude** [comment]
Hello @udaykumar-8329 , is there any update on this? Kindly let me know.

**Comment by SohanTirpude** [comment]
Hello @udaykumar-8329, kindly provide me an update on this.

**Comment by udaykumar-8329** [comment]
Hi @SohanTirpude , sorry for the delay... we will let you know once we test it... Thank you!

**Comment by SohanTirpude** [comment]
Hello @udaykumar-8329, did you get a chance to test it? Kindly let me know.

**Comment by SohanTirpude** [comment]
Hello @udaykumar-8329, did you get a chance to test it? Kindly let me know.

**Comment by SohanTirpude** [comment]
Hello @udaykumar-8329, did you get a chance to test it? Kindly let me know.

**Comment by SohanTirpude** [comment]
Hello @udaykumar-8329, 

You are not responding hence I am closing this ticket. I hope you are not facing this issue anymore, but If you are still facing the same issue, kindly let me know, I'll re-open the ticket.

If you are facing any other issues, kindly open a new ticket.
